BIDMCDigitalPsychiatry/LAMP-server

src/utils/ActivitySchedulerJob.ts

fix participant not stored in redis

#fix participant not stored in redis

---

package.json
src/app.ts
src/repository/SensorEventRepository.ts
src/utils/ActivitySchedulerJob.ts
src/utils/queue/DeleteFromSchedulerQueue.ts
src/utils/queue/SchedulerDeviceUpdateQueue.ts
src/utils/queue/SchedulerQueue.ts
src/utils/queue/UpdateToSchedulerQueue.ts

- Mutex lock for redis transactions
- Filter is added to sensoreventrepository._select to ignore the dashboard detail
- Activities based on participant logic changed

Resolve duplicate/missing device push notifications

---

src/utils/ActivitySchedulerJob.ts

Fix  not firing notification issue

#fix notification firing issue

---

src/utils/ActivitySchedulerJob.ts
src/utils/queue/SchedulerDeviceUpdateQueue.ts

# fix notification issue

---

src/utils/queue/SchedulerQueue.ts

- Notification Id should be an integer for Android

#fix android  notifications

---

src/utils/queue/SchedulerQueue.ts

Android notification payload fix master

Android notication payload fix master

---

src/utils/queue/SchedulerQueue.ts

fix removed to parameter from payload to resolve push notification

#fix removed to parameter from payload to resolve push notification

---

src/service/SensorEventService.ts
src/utils/ActivitySchedulerJob.ts
src/utils/queue/SchedulerQueue.ts

#fixes push notifications to be not fired while logout

---

package.json
src/app.ts
src/service/ActivityEventService.ts
src/service/ActivityService.ts
src/service/ParticipantService.ts
src/service/ResearcherService.ts
src/service/SensorService.ts
src/service/StudyService.ts
src/service/index.ts
src/utils/ListenerAPI.ts
src/utils/PushNotificationAPI.ts
src/utils/index.ts
src/utils/queue/PubSubAPIListenerQueue.ts
src/utils/queue/PushNotificationQueue.ts
src/utils/queue/SchedulerQueue.ts

- Listener api
- Publishing changes to apis

Implement Pub/Sub API using SSE via NATS

---

src/service/ResearcherService.ts

fix  token removed from payload

#fix  token removed from payload

---

src/utils/PushNotificationAPI.ts

removing existing job id from the push notification queue properly

removing existing job id from the queue properly

---

src/utils/queue/PubSubAPIListenerQueue.ts

fixes nats error to be shown as disconnected

#fixes nats error to be shown as disconnected

---

src/utils/ActivitySchedulerJob.ts
src/utils/PushNotificationAPI.ts

#filtering for fetching device token

#fixes notification - excluding type as open_page

---

src/utils/index.ts

added new index in activity db

#fixes activity indexing

---

src/service/ActivityEventService.ts
src/service/ParticipantService.ts
src/utils/ListenerAPI.ts
src/utils/queue/PubSubAPIListenerQueue.ts

#fixes nats payload error 
- publishing ids instead of whole data

#fixes nats payload error - Publishing ID instead of whole data

---

src/repository/Bootstrap.ts
src/service/ActivityService.ts
src/service/ResearcherService.ts
src/service/SensorService.ts
src/service/StudyService.ts
src/utils/ListenerAPI.ts
src/utils/queue/PubSubAPIListenerQueue.ts

fixes nats connection, fixes in delete operation in some apis

#fixes nats connection, fixes in delete of some apis

---

src/repository/SensorRepository.ts

#fixes sensor api

---

src/utils/queue/SchedulerQueue.ts

#fixes logs for investigation

---

src/model/Credential.ts
src/repository/Bootstrap.ts

- removed DB_DRIVER from env
- Kept DB in env to support both couch as well as mongo connection strings.

#fixes removed DB_DRIVER from db driver switch logic

---

package.json
src/repository/Bootstrap.ts
src/repository/couch/ActivityRepository.ts
src/repository/couch/ParticipantRepository.ts
src/repository/couch/SensorRepository.ts
src/repository/interface/RepositoryInterface.ts
src/repository/mongo/ActivityRepository.ts
src/repository/mongo/ParticipantRepository.ts
src/repository/mongo/SensorRepository.ts
src/service/ResearcherService.ts
src/utils/queue/CacheDataQueue.ts

#fixes api optimization in researcher

#fixes api-optimization in researcher

---

src/utils/queue/CacheDataQueue.ts

#fixes data cacheing for 5 minutes

---

src/repository/Bootstrap.ts

fixes redis-connection and dbname removal from mongo connection

#fixes redis-connection and dbname removal from mongo connection

---

src/repository/couch/ActivityRepository.ts
src/repository/couch/ParticipantRepository.ts
src/repository/couch/SensorRepository.ts
src/repository/interface/RepositoryInterface.ts
src/repository/mongo/ActivityRepository.ts
src/repository/mongo/ParticipantRepository.ts
src/repository/mongo/SensorRepository.ts
src/service/ResearcherService.ts
src/service/TypeService.ts

- fixes removal of researcher keys while login
- Issue fix in api

#fixes removal of researcher keys while login

---

src/repository/couch/ActivityRepository.ts
src/repository/couch/ParticipantRepository.ts
src/repository/couch/SensorRepository.ts
src/repository/interface/RepositoryInterface.ts
src/repository/mongo/ActivityRepository.ts
src/repository/mongo/ParticipantRepository.ts
src/repository/mongo/SensorRepository.ts
src/service/ResearcherService.ts

#fixes optimizing repo functions

---

src/model/Sensor.ts
src/service/StudyService.ts

#fixes study clone feature

---

src/repository/mongo/ActivityEventRepository.ts
src/repository/mongo/SensorEventRepository.ts

fixes query with timestamp in activity_event and sensor_event

#fixes query with time stamp in activity_event and sensor_event

---

src/service/ActivityService.ts

#fixes skip binary data based on query param given

#fixes skip binary data based on query param given

---

src/service/StudyService.ts

fixes await in study create api

#fixes await in study api

---

src/repository/mongo/ActivityRepository.ts
src/service/ActivityService.ts

- Avoid binary data in mongo repo as we did in couch repo
- Ignore photo to be published in nats in activity api

Jsonata branch fixes

---

src/service/SensorService.ts

fixes sensor delete in sensor api

#fixes sensor delete in sensor api

---

src/service/StudyService.ts
src/utils/queue/CacheDataQueue.ts

1. Service is managed to create study even if the study id to get cloned is not given

#fixes study clone logic change if no study id is given

---

src/service/SensorEventService.ts
src/utils/queue/BulkDataWrite.ts
src/utils/queue/BulkDataWriteQueue.ts

- batch update for sensor_events to reduce frequent db writes

#fixes batch update for sensor event

---

src/repository/mongo/ActivityEventRepository.ts
src/repository/mongo/SensorEventRepository.ts

- fixes querying in sensor_event and activity_event with upper limit

#fixes Event querying upper limit  in sensor_event and activity_event

---

src/utils/queue/BulkDataWrite.ts

-applied limit to be inserted in sensor_event database

#fixes sensor_event batch update

---

package-lock.json
package.json

- updated ajv
- removed two dev dependency packages

#fixes vulnerabilities

---

src/service/SensorEventService.ts

#fixes applied bulkdatawrite in sensor_event

---

Dockerfile

Addresses CVE-2021-23362 , CVE-2021-27290.

Security update

---

src/utils/queue/BulkDataWrite.ts

- created logs in batch update

#fixes logs in batch update of sensor_event

---

src/utils/queue/BulkDataWrite.ts
src/utils/queue/BulkDataWriteQueue.ts

- added more logs and delay changed

#fixes logs in batch update

---

src/repository/couch/SensorEventRepository.ts
src/repository/interface/RepositoryInterface.ts
src/repository/mongo/SensorEventRepository.ts
src/utils/queue/BulkDataWrite.ts
src/utils/queue/BulkDataWriteQueue.ts

- Implemented a new function to write bulk data

#fixes sensor event batch update

---

src/repository/mongo/SensorRepository.ts

include spec in sensor lookup api

#fixes sensor_spec in lookup api

---

src/service/SensorEventService.ts
src/utils/queue/BulkDataWrite.ts

- implemented to publish last set of data in sensor_event  post api

#fixes sensor_event bulk write update

---

src/repository/couch/CredentialRepository.ts
src/repository/couch/TypeRepository.ts
src/repository/mongo/ActivitySpecRepository.ts
src/repository/mongo/CredentialRepository.ts
src/repository/mongo/SensorSpecRepository.ts
src/repository/mongo/TypeRepository.ts
src/service/TypeService.ts

- user hierarchy changes in tag and credential
-  fixes in activity and sensor spec listing

#fixes user hierarchy-changes, activity-sensor spec fix in listing

---

src/service/SensorEventService.ts

- Removing sensor events caching to check the data loss issue

#fixes remove sensor_event caching

---

src/service/OAuthService.ts
src/service/index.ts
src/utils/OpenAPISchema.json

Create Start OAuth Flow Endpoint

---

src/repository/couch/TypeRepository.ts
src/repository/mongo/TypeRepository.ts
src/service/Security.ts
src/service/TypeService.ts

Reverts BIDMCDigitalPsychiatry/LAMP-server#221

Revert "#fixes server wide tags"

---

src/repository/mongo/CredentialRepository.ts
src/service/CredentialService.ts

@avaidyam I've been adding a basic UI to test the feature and I found some issues with the server side code.
Now it's working as expected!

Fix some issues after testing the feature

---

README.md

No change update to redeploy to dev.

No change update to README.md to redeploy to dev 
